version:  '3'
services:
  datascience-notebook:
      image: jupyter/datascience-notebook
      ports:
        - 8888:8888
      container_name: jupyter_notebook
      volumes:
      - ${PWD}:/home/jovyan/work