version:  '3'
services:
  datascience-notebook:
      build:
        context: .
        dockerfile: Dockerfile
      image: localhost/insomnius-jupyter-notebook
      ports:
        - 8888:8888
      container_name: jupyter_notebook
      volumes:
      - ${PWD}:/home/jovyan/work