version:  '3'
services:
  datascience-notebook:
      image: jupyter/datascience-notebook
      ports:
        - 8888:8888
      container_name: jupyter_notebook
      volumes:
      - aiindonesia_repository:${PWD}

volumes:
  aiindonesia_repository:
    name: aiindonesia_repository