run:
	@echo "==========================================="
	@echo "Task: 2_1"
	@poetry run python python_course/2_1.py
	@echo "==========================================="
	@echo "Task: 2_2"
	@poetry run python python_course/2_2.py
	@echo "==========================================="
	@echo "Task: 2_3"
	@poetry run python python_course/2_3.py
	@echo "==========================================="
	@echo "Task: 2_4"
	@poetry run python python_course/2_4.py
	@echo "==========================================="
	@echo "Task: 2_5"
	@poetry run python python_course/2_5.py
	@echo "==========================================="
	@echo "Task: 2_6"
	@poetry run python python_course/2_6.py
	@echo "==========================================="
	@echo "Task: 3_1"
	@poetry run python python_course/3_1.py
	@echo "Task: 3_2"
	@poetry run python python_course/3_2.py